### ISSUE TITLE
Remove autoconf support

### ISSUE THREAD

**Issue by schancel** [cashweb/cashd#8]
Autoconf is archaic and support for it should be removed.  Nuff said.

**Comment by cculianu** [comment]
Use CMake?

**Comment by schancel** [comment]
CMake is already implemented.  Autoconf was left there for some QT stuff.  We can delete it.

**Comment by cculianu** [comment]
That's awesome. I didn't know that. When I worked on this code it was all autoconf.  Great!

**Comment by schancel** [comment]
I think this was done. Closing.
